### ISSUE TITLE
Question about decision...

### ISSUE THREAD

**Issue by allantorres** [nitemarket/FormMessenger#1]
Hi, your script is amazing but i don't find anything about decisions in the form, like change the question based on the previous anwser... so did you can help on that? 

Thank's for your time!

**Comment by nitemarket** [comment]
Hi Allan, I'm glad that you have found this but the documentation is still in draft.
For your question in changing the question based on previous answer, do you mean the option `previousResponsePattern`? 
(1) If **yes**, it allows you to insert user's previous answer into the next question. Use case: 
```javascript
<input type="text" name ="name" placeholder="Full Name">
<input type="text" fm-questions="Hi {{previousResponse}}. Let me know your gender!">
```
The default pattern is `{{previousResponse}}` but you can change it by setting `previousResponsePattern` option to new value.

(2) If **no**, you may mean skip/changing to different question within a form after an answer. This feature is not supported at the moment. The questions are asked based on pre-defined html form. However, you can **switch form** easily after an input from user. For example, you can ask user to switch to forget-password form if they insert wrong credential.

Hope this will help you.

**Comment by allantorres** [comment]
My case is the case 2 ... 
But i will try to implement that! 
thank's !
